### ISSUE TITLE
Move to core

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-lcg#1]
@paf31 mind if I move this to core? Seems useful to have as a thing independent of QC - I'd at least like to use it in SC as I'm pretty sure the LCG there doesn't behave well.

I did consider adding a type that works with `MonadGen`, but it's basically QC's `Gen`, so 🤷‍♂️ 😄

**Comment by paf31** [comment]
Sure, looks good, thanks!

Looks quite like what's in QC from memory, but I haven't looked. Is it the same?

**Comment by garyb** [comment]
Yeah, pretty much - I lifted it from there and just shuffled the code around a bit. I did rename the `lcg` constants though, to match the algorithm as described on wikipedia (m rather than n for modulus, a rather than m for multiplier).

Because of that I'll switch QC to this when we do 0.12 / 1.0, whichever we do next.
